# **PANDAS**

Pandas in python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data.

Pandas allows us to analyze big and make conclusions based on statical theories. Pandas can clean messy data sets, and make them readable and relevant .

Relevant data is very important in data science.

In Pandas, One dimension is called Series. Two dimension is called Data Frame and Three dimension is called Panel.

# **SERIES GENERATION (1 DIMENSION)**

In [ ]:
#SERIES GENERATION

import pandas as pd

data = [3,4,5,8]

s = pd.Series(data)

print(s)

<class 'list'>
0    3
1    4
2    5
3    8
dtype: int64

In [ ]:
#arrays in series

import pandas as pd
import numpy as np

data = np.array([4,5,6,7])

print(type(data),'\n')

s = pd.Series(data)

print(s)

<class 'numpy.ndarray'>

0    4
1    5
2    6
3    7
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

data = np.array([[4,5,6,7],[1,2,3,4]])

s = pd.Series(data)

print(s)

ValueError: Data must be 1-dimensional, got ndarray of shape (2, 4) instead

In [ ]:
#LIST

import pandas as pd

import numpy as np

data1 = [1,3,5,7,9]

print(type(data1),'\n')

s = pd.Series(data1)

print(s)

<class 'list'>

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
#TUPLE

import pandas as pd

data2 = (10, 20, 30, 40, 50)

print(type(data2),'\n')

series = pd.Series(data2)

print(series)

<class 'tuple'>

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:

import pandas as pd

data = (4,5,6,7)

s = pd.Series(data)

print(s,'\n')

print('Shape : ',s.shape)

print('Dimension : ',s.ndim)

print('D',s.dtype)

0    4
1    5
2    6
3    7
dtype: int64

Shape :  (4,)
Dimension :  1
D int64

# **Custom Indexing**

In [ ]:
#INDEXING

import pandas as pd

import numpy as np

data = ([4,5,6,7])

s = pd.Series(data,index = [100,101,102,103])

print(s)

100    4
101    5
102    6
103    7
dtype: int64

In [ ]:
#DICTIONARY

import pandas as pd

data = {1:'shaluu',2:'nasrn',3:'fathm'}

s = pd.Series(data)

print(s)

1    shaluu
2     nasrn
3     fathm
dtype: object

In [ ]:
#INDEXING


import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s)

5       NaN
1    shahla
8       NaN
2     fathm
3      nsrn
4       NaN
dtype: object

In [ ]:
#INDEXING A PARTICULAR VALUE

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[3])

nsrn

In [ ]:
#INDEXING MULTIPLE VALUES

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[[1,2,3]])

1    shahla
2     fathm
3      nsrn
dtype: object

In [ ]:
#SLICING

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[0:3])

5       NaN
1    shahla
8       NaN
dtype: object

# **DATA FRAME (2 DIMENSION)**

In [1]:
import pandas as pd
import numpy as np

data = [[3,4,5,6],[7,8,9,10]]

s = pd.DataFrame(data)

print(s)

   0  1  2   3
0  3  4  5   6
1  7  8  9  10

In [2]:
import pandas as pd
import numpy as np

data1 = [['Ram',1,2,3],['John',4,5,6]]

z = pd.DataFrame(data1)

print(z)

      0  1  2  3
0   Ram  1  2  3
1  John  4  5  6

In [3]:
import pandas as pd
import numpy as np

mark = {'Name': ['Shahla','Fathima','Nasrin'],'Maths': [40,60,50],'Physics': [40,60,50],'Chemistry' : [40,60,50]}

x = pd.DataFrame(mark)

print(x)

      Name  Maths  Physics  Chemistry
0   Shahla     40       40         40
1  Fathima     60       60         60
2   Nasrin     50       50         50

In [5]:
import pandas as pd
import numpy as np

mark = {'Name': ['Shahla','Fathima','Nasrin'],'Maths': [40,60,50],'Physics': [40,60,50],'Chemistry' : [40,60,50]}

x = pd.DataFrame(mark)

x['Biology'] = [44,50,60]

x['Total Mark'] = x['Maths'] + x['Physics'] + x['Chemistry'] + x['Biology']

print(x)

      Name  Maths  Physics  Chemistry  Biology  Total Mark
0   Shahla     40       40         40       44         164
1  Fathima     60       60         60       50         230
2   Nasrin     50       50         50       60         210

In [19]:
import pandas as pd
import numpy as np

mark = {'Name': ['Shahla','Fathima','Nasrin'],'Maths': [40,60,50],'Physics': [40,60,50],'Chemistry' : [40,60,50]}

x = pd.DataFrame(mark)

x['Biology'] = [44,50,60]

x['Total Mark'] = x['Maths'] + x['Physics'] + x['Chemistry'] + x['Biology']

list1 = []


for i in x['Total Mark']:


  if i >= 200:

    list1.append('Excellent')

  elif i > 100:
    list1.append('Average')

  else:
    list1.append('Below Average')


x['Status'] = list1

print(x)

print(x[['Name','Status','Chemistry']])

      Name  Maths  Physics  Chemistry  Biology  Total Mark     Status
0   Shahla     40       40         40       44         164    Average
1  Fathima     60       60         60       50         230  Excellent
2   Nasrin     50       50         50       60         210  Excellent
      Name     Status  Chemistry
0   Shahla    Average         40
1  Fathima  Excellent         60
2   Nasrin  Excellent         50

In [22]:
import pandas as pd
import numpy as np

mark = {'Name': ['Shahla','Fathima','Nasrin'],'Maths': [40,60,50],'Physics': [40,60,50],'Chemistry' : [40,60,50]}

x = pd.DataFrame(mark)

x['Biology'] = [44,50,60]

x['Total Mark'] = x['Maths'] + x['Physics'] + x['Chemistry'] + x['Biology']

list1 = []


for i in x['Total Mark']:


  if i >= 200:

    list1.append('Excellent')

  elif i > 100:
    list1.append('Average')

  else:
    list1.append('Below Average')


x['Status'] = list1

del x['Chemistry']

x = x.drop('Physics', axis = 1) #want to specify axis

x.pop('Maths')

print(x)

      Name  Biology  Total Mark     Status
0   Shahla       44         164    Average
1  Fathima       50         230  Excellent
2   Nasrin       60         210  Excellent

In [27]:
import pandas as pd
import numpy as np

mark = {'Name': ['Shahla','Fathima','Nasrin'],'Maths': [40,60,50],'Physics': [40,60,50],'Chemistry' : [40,60,50]}

x = pd.DataFrame(mark)

x['Biology'] = [44,50,60]

x['Total Mark'] = x['Maths'] + x['Physics'] + x['Chemistry'] + x['Biology']

list1 = []


for i in x['Total Mark']:


  if i >= 200:

    list1.append('Excellent')

  elif i > 100:
    list1.append('Average')

  else:
    list1.append('Below Average')


x['Status'] = list1

print(x)

print(x.ndim)
print('\n')
print(x.shape)
print('\n')
print(x.size)
print('\n')
print(x.columns)
print('\n')
print(x['Status'].unique())
print('\n')
print(x['Biology'].unique())
print('\n')
print(x['Status'].value_counts())

      Name  Maths  Physics  Chemistry  Biology  Total Mark     Status
0   Shahla     40       40         40       44         164    Average
1  Fathima     60       60         60       50         230  Excellent
2   Nasrin     50       50         50       60         210  Excellent
2


(3, 7)


21


Index(['Name', 'Maths', 'Physics', 'Chemistry', 'Biology', 'Total Mark',
       'Status'],
      dtype='object')


['Average' 'Excellent']


[44 50 60]


Status
Excellent    2
Average      1
Name: count, dtype: int64

In [37]:
print(x.head())

      Name  Maths  Physics  Chemistry  Biology  Total Mark     Status
0   Shahla     40       40         40       44         164    Average
1  Fathima     60       60         60       50         230  Excellent
2   Nasrin     50       50         50       60         210  Excellent

In [28]:
print(x.head(2))

      Name  Maths  Physics  Chemistry  Biology  Total Mark     Status
0   Shahla     40       40         40       44         164    Average
1  Fathima     60       60         60       50         230  Excellent

In [30]:
print(x.tail(1))

     Name  Maths  Physics  Chemistry  Biology  Total Mark     Status
2  Nasrin     50       50         50       60         210  Excellent

In [31]:
print(x.describe())

       Maths  Physics  Chemistry    Biology  Total Mark
count    3.0      3.0        3.0   3.000000    3.000000
mean    50.0     50.0       50.0  51.333333  201.333333
std     10.0     10.0       10.0   8.082904   33.842774
min     40.0     40.0       40.0  44.000000  164.000000
25%     45.0     45.0       45.0  47.000000  187.000000
50%     50.0     50.0       50.0  50.000000  210.000000
75%     55.0     55.0       55.0  55.000000  220.000000
max     60.0     60.0       60.0  60.000000  230.000000

In [32]:
print(x.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Maths       3 non-null      int64
 2   Physics     3 non-null      int64
 3   Chemistry   3 non-null      int64
 4   Biology     3 non-null      int64
 5   Total Mark  3 non-null      int64
 6   Status      3 non-null      object
dtypes: int64(5), object(2)
memory usage: 296.0+ bytes
None

In [33]:
print(x.sum())

Name                ShahlaFathimaNasrin
Maths                               150
Physics                             150
Chemistry                           150
Biology                             154
Total Mark                          604
Status        AverageExcellentExcellent
dtype: object

In [34]:
print(x['Biology'].sum())

154

In [35]:
print(x.sum(1))   # row wise

TypeError: can only concatenate str (not "int") to str

In [36]:
print(x.sum(0))   #column wise

Name                ShahlaFathimaNasrin
Maths                               150
Physics                             150
Chemistry                           150
Biology                             154
Total Mark                          604
Status        AverageExcellentExcellent
dtype: object

In [38]:
print(x['Maths'].mean())

50.0